recipient =  input("Enter the Recipient:")
message = input("Enter Message:")
name = input("Enter Name:")
subject = input("Enter Subject: ")
version = float(input("Enter Version:"))
discount = float(input("Enter Discount:"))
status = input("Enter Status:")
code = input("Enter Code:")
location = input("Enter Location:")
age = int(input("Enter Age:"))
companyName = input("Enter Company Name:")
website = input("Enter Website:")
phone = input("Enter Phone")
jobTitle = input("Enter Job Title:")
department = input("Enter Department:")


print(f"Dear {recipient}, I hope this email finds you well.\n")
print(f"{message}")
print(f"Subject: {subject}")
print(f"Sender: {name}")
print(f"Version: {version}")
print(f"Discount: {discount:.2f}%")
print(f"Status: {status}")
print(f"Code: {code}")
print(f"Location: {location}")
print(f"Age: {age}")
print(f"Company: {companyName}")
print(f"Website: {website}")
print(f"Phone: {phone}")
print(f"Job Title: {jobTitle}")
print(f"Department: {department}")

